<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>salesoption</name>
   <tag></tag>
   <elementGuidId>b7f7e3bb-ce84-456f-a9ee-63c58254c4cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//one-app-launcher-app-tile[2]//div[1]//div[2]//div[1]//a[1]//lightning-formatted-rich-text[1]//span[1]//p[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
