<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectclick</name>
   <tag></tag>
   <elementGuidId>50c812e5-ad6d-41e6-b402-3258d5d6fb9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[1]//td[10]//span[1]//div[1]//a[1]//lightning-icon[1]//lightning-primitive-icon[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
