<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1</name>
   <tag></tag>
   <elementGuidId>29ecdfce-73ee-4c31-904b-bba3d2eea71c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[title=&quot;Line Chart&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='YZAeLHgDf-modal-content']/div/div/div[3]/div/div/fieldset/label[5]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Line Chart</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;YZAeLHgDf-modal-content&quot;)/div[@class=&quot;componentEditor valid&quot;]/div[@class=&quot;infoPanel&quot;]/div[@class=&quot;eclairConfigurerRC&quot;]/div[@class=&quot;analyticsEclairConfigurer THIS&quot;]/div[1]/fieldset[@class=&quot;config-input config-input-chartselector&quot;]/label[@class=&quot;chart-picker-label&quot;]/div[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SF_Lightning/Sales/Dashboard_Object/Obj01_Rec_Create DB for Diff charts/Page_Test DB For Diff charts  Salesforce/iframe_Show actions_sfxdash-1608291687868-364660</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='YZAeLHgDf-modal-content']/div/div/div[3]/div/div/fieldset/label[5]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[5]/div</value>
   </webElementXpaths>
</WebElementEntity>
