<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Account_Create_Edit_Delete</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9041a39a-4788-4bf8-b779-edde805399f7</testSuiteGuid>
   <testCaseLink>
      <guid>4516b7ca-c2a7-46cc-b31f-a7f64137bb69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC01_Create Account from New Button</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>614a6989-4aee-46de-bcc2-ad9c9c0e1017</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1bb86f19-d091-4870-ae08-11222e1de552</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7e3da070-d966-4f65-b52e-9bdf013b3ac2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC03_Edit Account from Account list view</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>713a5187-c533-41a5-8308-7bb21b739a09</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fd6d75b-2505-435c-b378-8732e793231a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da079b9b-a47e-43b3-9eb7-5e3142be0e5f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC32_Delete Account from Account list view</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5a9e9f5-97b2-4eaf-bb91-f3c0de1718fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60ef1e8a-a690-44bd-9c99-67af130abee8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac862d8f-354e-405f-8b5f-9518170269a5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>97ddb2a5-57ae-4112-a29d-00f5544b0113</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC02_Create Account from Lead Conv</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c851a8c-ff70-490e-b56f-6f815c89a003</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1de5dbd-8115-444f-a653-349c08a64e40</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>97b5e38a-bb09-49bf-970e-2aa16e15a6fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC04_Edit Account from Account Details Page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>688639d9-cb67-493f-b753-6f04c57998f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>215a2ede-4728-472b-a5fa-7455a2ae781e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bc0a848e-3019-4460-85a3-1f28cedb967b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC33_Delete Account from Account Details Page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a08c617b-e766-42b9-8e20-fa210acca7c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1744fa7e-5839-4074-a22e-4e927e8440d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>989d9139-2e68-4eb5-941b-8fc5ecfc1f2c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
