<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Activities_Call Log_Event_Task_Create Edit Delete</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>8e6931fa-219d-47dd-a0c9-c3218313df10</testSuiteGuid>
   <testCaseLink>
      <guid>2b4ff4d3-4c1e-4e19-b88f-6cf2ebc25852</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC19_Log a Call_From Account Details Page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d28d2ed5-fab3-4966-987e-0497a17a9c1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47f4a2fc-22d6-4cb4-96be-42fd99893d06</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4a751327-3d86-427a-9f94-5937fea0f198</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC20_Create a task_From Account Details Activity tab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85695d60-6407-4157-9a73-fb680abca7c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e579cf4f-34cc-4acd-8c5f-6995eb0af42d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>38a1e7e3-a071-49d4-b04f-b9e096039e9a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC21_Edit task_From Account Details Activity tab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1168f5e-0b86-4dff-ac48-c8785a143a5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cc18332-4029-4f73-aa6b-75d04cb5fb11</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c6afc237-408f-4906-8e53-45f6e6d65bc3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC22_Delete Task_From Account Details Activity tab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bff27b0-43e0-4ebd-b032-ca2a908610b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>042c0124-4932-4903-9fb0-28d92f8e65a9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c85c14b4-19a5-475a-aba6-984d40c0277d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC23_Create a Event_From Account Details More tab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcf98e16-92cc-4a08-8649-fc5006cbd69a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf6e0634-eebf-49d8-a174-ce0bd342b5b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b32e103a-604c-43d0-b044-5ca9607ef629</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC24_Edit a Event_From Account Details More tab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2fcb618-4dc6-44df-809a-52cb26c375db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>151cd024-7838-4c2d-af06-6b7a25739f6c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5978fb5c-a512-4963-8aa8-219b1422ff79</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC25_Delete a Event_From Account Details More tab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>839d9e0f-75ab-4abe-bea2-57a8b741a7cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7580c634-aa2e-45c3-8891-4f8b684d831d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
