<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Related List_Contact_Create Edit Delete</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>56d2805e-4ed9-43c2-9a4d-85edc9e58b77</testSuiteGuid>
   <testCaseLink>
      <guid>fcf63f80-3ae9-4120-b58f-cba390589c69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC07_Create Contact_From Account Related List</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac0cccb2-50c8-4cbc-b8f1-dbea9fec7313</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef17efe2-0a0f-4753-a499-d4e355d742a0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ef7a004a-2216-492b-aa82-b6aa3e52d153</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC09_Edit Contact_From Account Related List</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09673ad8-6242-4c67-9556-55c0804c90b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27e8a300-bf9a-4758-b858-fc7bdd7883f6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>488caff2-7b32-4df8-94ca-c46bfd3928b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC11_Delete Contact_From Account Related List</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64a76128-cd9c-4de6-92ed-f5e795fd4289</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adbe0c43-fcf4-4ff8-9781-2645c9182fca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eb9cc362-afb3-47e3-a2b0-a9bd1de6b1cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC08_Create Contact_From Account Details Page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5142513-a9c1-4993-b7de-d3494264c21a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7bcdf8ef-e755-40bb-839b-cef2ba432353</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>deeb3052-9fac-44a2-b00b-fe3b1ecc44b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC10_Edit Contact_From Account Related List Details Page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de381e17-e550-4daf-a606-7a2f8cc0664f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f72da80e-e265-4b15-891b-32c05bf4da19</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b8cafbcb-0f0b-4aa0-a82d-ac7bfb5c945e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC12_Delete Contact_From Account Related List Details Page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b8d7e48-34a1-4a47-b582-2507937dc30e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec43cb9c-4294-4b85-99ad-1c5eeda70cab</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
