<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Related List_Opportunities_Create Edit Delete</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>72ce3681-f30d-4f5f-a8bc-018550863361</testSuiteGuid>
   <testCaseLink>
      <guid>f180988e-7ccb-4c0f-b88b-6e3b4661bd39</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC13_Create Opp_From Account Related List</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3eda8f7-bb3e-4da0-bf8e-76688e1c5040</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a07bf256-26b7-4f54-9eb5-d50d61278435</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>85fcac2d-7767-40e8-9fa4-d1a3b866bb51</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC14_Edit Opp_From Account Related List</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c10d6ef9-23c2-4e10-9af1-6087c4b2976e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffa18297-1f97-4651-8ce8-7dabca926d6c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9897376a-87a6-49d5-afaa-37ffa6162ad6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC16_Delete Opp_From Account Related List</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c48b1982-d2df-420d-9cc9-8b081edd3d3f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>040e3bcd-45a8-4c48-98e9-90c1301897c8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff9da8bf-fa59-4996-ae33-02c5e8d12592</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC18_Create Opp_From Account Details Page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32d4f8e0-95ca-443c-8d7a-305a3e424885</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>798f6516-d5d6-46c8-85fa-0ab205b19efc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f30b4088-440c-4eed-aca1-152ee4e1ebe5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC15_Edit Opp_From Account Related List_Opp Details Page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c60751be-001d-4eb9-bf93-989b093de6fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83de053c-215a-40ee-bd79-1a3df224ff5a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a881d7db-5779-43e2-b8a1-4bc5b85b64e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC17_Delete Opp_From Account Related List_Opp Details Page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cab6c6e-1e6e-42f6-ac56-5be98dee492c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e663e12d-a45b-439c-b28a-1113af10cad4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
