<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Related List_Case_Create Edit Delete</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4d572544-d4d8-491e-ba00-dd4a54540606</testSuiteGuid>
   <testCaseLink>
      <guid>70533bf7-56ad-4327-94fa-5358727205f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC26_Create Case_From Account Related List</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a76d758f-db0f-4c27-ab35-3b832e8d1de7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c8a6c1f-6252-4b75-8f13-46a796a2e4b0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>030897f5-5765-4d6e-9351-cfdbeb0cfe28</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC28_Edit Case_From Account Related List</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a453fd9-c41c-4831-9890-f77111e35a1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a57202f2-ff2e-4c03-babf-db66fee74d48</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8b3f3236-b336-4b01-b44e-072162b9b6f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC30_Delete Case_From Account Related List</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04ca9f95-22fc-43ef-a639-b10ca26649aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20b357c8-c7c4-4ea0-b36f-3d5c6bc2a3e6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>93cc3e0e-76aa-4e1e-986a-b9c04332324e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC27_Create Case_From Account Details Page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>190a7ab2-1419-4af1-8d16-cb2684b36189</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00cda673-c738-4588-b5f2-d425b831f0a9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6bc81f86-fee6-4c7b-90f0-e7814a121e36</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC29_Edit Case_From Account RL Case List Page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ace327b6-2f68-442c-8ac8-f4234645299d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3e9b91f-1f3d-472c-b3cb-f1389c33a8b5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9c3c8bfe-e2ed-46cf-a7f9-4b83c7a14e7e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Account_Object/TC31_Delete Case_From Account RL Case List Page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68078746-6c81-43b6-a0e1-5f6407ce79d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3b19147-f9b8-413d-948e-9eb93f3eb705</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
