<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select</name>
   <tag></tag>
   <elementGuidId>f57d85b0-51e7-4d8e-80a1-434ff6877690</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mark[contains(text(),'campaigntest')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
