<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Report for Account</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>763d334d-3a67-4057-bf55-d0424b60588d</testSuiteGuid>
   <testCaseLink>
      <guid>dfccc248-32be-48e3-b0ec-95a9a42a8ef8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Report_Object/TC11_Create Report for Account</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe8bd880-5b17-4d2d-a8b3-84366b456e87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>498b6fd7-dcac-42b9-8dd2-50425c71cac1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f2990540-6fbf-43f2-a398-a0f274dbf7ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Report_Object/TC12_Create Report for Account and Contacts</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2299512-6be6-4273-9878-36934b2ea7d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba556e91-3b21-47a7-9725-55ceadf54a9f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>14e73bfd-81a3-4678-a680-622f2e507ed2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Report_Object/TC13_Create Report for Accounts with Partners</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13f0c634-41d5-4f95-b4f2-7a36a7f761f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd15ed96-f5c9-429d-8ed2-06b70681ef67</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ed290453-7582-407c-bd57-4385aeefc494</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Report_Object/TC14_Create Report for Account with Account Teams</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60b37e53-5fed-4528-b4e3-809b01b59df2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6771c46f-04d2-45bf-8268-e758402a4784</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6e3be3d1-3f74-436b-85e7-aa9a12bb5166</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Report_Object/TC15_Create Report for Accounts with Contact Roles</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d7a9818-aaea-4bdd-97f3-880292eae7b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a860f3e-9653-40fa-b569-fb57b83e7347</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9d180910-2186-4903-b170-c481914837de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Report_Object/TC16_Create Report for Accounts with Assets</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d015192-9369-4f06-9853-bd2a65d8867d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>071556cf-fe80-4b25-abad-7903310d32f7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8dea6fd7-2a30-43b8-a747-4f3234217c99</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Report_Object/TC17_Create Report for Account History</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f82e07bc-3242-4021-9c5a-2b80dc72779a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfd05989-7dc8-4028-b1ba-9b80a18ba462</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f618c3ae-6483-415c-8632-8663fabb57fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Report_Object/TC18_Create Report for DB Company with and without Accounts</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77a2121b-02ba-4c73-859b-73d52c2ea37c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd5f1455-217d-46fb-b6a8-253898e16ec2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8e52ad78-8b99-4b5b-9ec7-0b06bb9c3389</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Report_Object/TC19_Create Report for Accounts with Entitlements with Contacts</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a8ef9e1-6a1c-4122-8d40-27fb8d5f5200</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77451bc2-b828-410f-bbcf-fadf586a8991</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bd5e80de-fcb7-4ef9-9e92-4ae8ef56ad6f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Report_Object/TC20_Create Report for contact history</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1d6aebb-7798-4207-a7df-718d1dec3a11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d1c080b-89b7-4fc6-ba0b-86a2bd059d1f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>323607b1-8163-410f-b3b7-412db7ec6a82</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Report_Object/TC21_Create Report for contacts with assets</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>327e3c17-9ff6-46c9-bbe9-6bdbb93228a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62e9a39a-5c2b-4cf2-83c2-a6133ca6e9d9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
