<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Report for Contacts</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a0ec0021-982c-4280-ab40-cf9a51ef80e9</testSuiteGuid>
   <testCaseLink>
      <guid>02bd894d-3a72-4faf-b2ac-f1bf109b7baf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Report_Object/TC20_Create Report for contact history</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1d6aebb-7798-4207-a7df-718d1dec3a11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d1c080b-89b7-4fc6-ba0b-86a2bd059d1f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ffe8aff2-eaf3-47a3-b508-524012002bc4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SF_Lightning/Sales/Report_Object/TC21_Create Report for contacts with assets</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>327e3c17-9ff6-46c9-bbe9-6bdbb93228a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62e9a39a-5c2b-4cf2-83c2-a6133ca6e9d9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
