<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>optionsel</name>
   <tag></tag>
   <elementGuidId>32bdadc1-339e-4840-a209-36ca9b0edf76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[1]//td[10]//span[1]//div[1]//a[1]//lightning-icon[1]//lightning-primitive-icon[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
